// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVH0b0KdbDec0BzitBvIF0KAIK_ArXIgs',
    appId: '1:662652421977:web:372752f60f6025654bae48',
    messagingSenderId: '662652421977',
    projectId: 'genesis-deed1',
    authDomain: 'genesis-deed1.firebaseapp.com',
    storageBucket: 'genesis-deed1.firebasestorage.app',
    measurementId: 'G-ZVH0NX408T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPziuOQEmxT5PTlGb7mQvt39qeLYxNRhw',
    appId: '1:662652421977:android:6ed1fdd0f247e6aa4bae48',
    messagingSenderId: '662652421977',
    projectId: 'genesis-deed1',
    storageBucket: 'genesis-deed1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW2gHTLpL1WEOs08aVMoCkpfidS5krYPw',
    appId: '1:662652421977:ios:f20aa1cf90cc1f7b4bae48',
    messagingSenderId: '662652421977',
    projectId: 'genesis-deed1',
    storageBucket: 'genesis-deed1.firebasestorage.app',
    iosBundleId: 'com.genesis.system',
  );
}
